### PR TITLE
complete-authorization-request: fix error handling

### LINKED ISSUE #134: completeAuthorizationRequestIfPossible: error handling
Hi,

I've been facing an issue in a project  related with the `completeAuthorizationRequestIfPossible` function in `authorization_request_handler.ts`.

The problem is that if I refresh my website during the complete authorization process it may end up in an incosistent state. The reason is that the function [completeAuthorizationRequest](https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts) returns a null value because it cannot find the related authorization request local storage value. 
In this situation, the authorization flows stops in [completeAuthorizationRequestIfPossible](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L128) with the log `No result is available yet`. 

So my request is: **Would you consider calling `notifier.onAuthorizationComplete` also in error cases?** The function is prepared for that and in this way the error handling would be delegated in the user code through the  [setAuthorizationListener](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L139) function instead of dying in the libray code.

Thanks in advance

### PR DESCRIPTION
**Pull request by jnoga**
It's been a while since I report this issue, with this PR the possible `No result is available yet` error in `completeAuthorizationRequestIfPossible` function is delegated in the final client code.

Hope you approve it.

Fixes #134

### CODE REVIEW

**Comment by tikurahul** [comment]
That is not a change i want to make. You could treat that case as an error and start the full flow all over again - or keep track of the fact that you did not complete the flow another way.

**Comment by jnoga** [comment]
Hi @tikurahul 

I've tried again what you suggested, but I couldn't get what I wanted. 

> You could treat that case as an error and start the full flow all over again

The main idea of this PR was to treat this error case and be able to start the full fllow again. So maybe there is something I may not understand on your code.

From what I see, any result in `completeAuthorizationRequest` it is supposed to be treated by `completeAuthorizationRequestIfPossible` and be delegated to the notifier's `AuthorizationListener` function I declare in my code. When everything goes fine, the notifier's listener is called, but when something goes wrong, nothing is done. I mean the only action taken is to log the message `Not result available yet`, the code flow dies there. `completeAuthorizationRequestIfPossible` returns a void promise, because (I assume)  the responsible to handle any case should be the notifier's `AuthorizationListener` function called by `onAuthorizationComplete`.

Summarizing I don't see any way to treat this case as an error if I cannot get the error from the `AuthorizationListener`, something that currently is not done. Am I right or is there something I'm missing? How would you treat the error case? 

Any help is much appreciated, thanks in advance

**Comment by thecopy** [comment]
@tikurahul Could you please expand on how it is possible to treat this case as an error? There is no notification happening in this scenario. 

The only approach i can see it to set a timeout and clear that in the notification callback. But this is not an approach i like.

From your message it seems that there is some way of detecting the outcome "Not result available yet" from a `completeAuthorizationRequestIfPossible`-call. Could you expand? I dont find this either in the documentation or in the source-code.

**Comment by aberasarte** [comment]
We are suffering the same issue reported by @jnoga and I think that this PR would help us. @tikurahul I don't get what you mean when you say: 

> You could treat that case as an error and start the full flow all over again

As far as I see, the problem is precisely that some errors are not handled by the library and therefore, we as the consumers can't do anything about it.

**Pull request closed without merging**
