### PR TITLE
Include refresh_expires_in in TokenResponse #160

### PR DESCRIPTION
**Pull request by vdeygas**

### CODE REVIEW

**Comment by tikurahul** [comment]
This property is not a part of the [RFC](https://tools.ietf.org/html/rfc6749#section-5.1). I recommend extending `TokenResponse` to make it do what you need.

**Comment by vdeygas** [comment]
Turns out that Keycloak does not conform to the RFC. You are right, the RFC does not include refresh_expires_in in the token response of the authorization code flow.

I guess this can be closed then. 😔

But, unless I'm mistaken, `id_token` isn't either ?

**Comment by vdeygas** [comment]
Hum, ok, I think it's because id_token is part of OpenID Connect spec.

**Comment by vdeygas** [comment]
You recommend me to extends TokenReponse. What does it means ?

**Comment by tikurahul** [comment]
I meant that you should extend the class `TokenResponse` and `TokenResponseJson`.

**Pull request closed without merging**
