### PR TITLE
Added option to change authorization request parsing from hash to query

### PR DESCRIPTION
**Pull request by C45tr0**
Added optional options param, which includes `useHashForAuthorization` to be able to specify how the OAuth server returns its authorization response, in the RedirctBasedHandler.

### CODE REVIEW

**Comment by tikurahul** [comment]
Thanks for this. So you have always been able to do something like this by doing:

```ts
class NoHashQueryStringUtils extends BasicQueryStringUtils {
  parse(input: LocationLike, useHash?: boolean): StringMap {
    return super.parse(input, false /* never use hash */);
  }
}
```

Then you can use instantiate your own `RedirectBasedHandler` like so:

```ts
new RedirectRequestHandler(
  undefined /* default storage backend */ , 
  new NoHashQueryStringUtils(),
  undefined /* default locationLike */);
```

Hope that helps. You don't need to introduce more flags.

**Comment by selfissued** [comment]
It would be good to understand how this relates to the `response_mode=query` request parameter defined in http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html .

**Comment by tikurahul** [comment]
I think this is applicable in other circumstances as well. If you take a look at the sample at:

https://github.com/openid/AppAuth-JS/blob/master/src/app/index.ts#L100

I am asking for a response_type `code` and specifying a `redirectUri`. My [`redirectUri` ](https://github.com/openid/AppAuth-JS/blob/master/app/redirect.html) gets the query parameters from the `redirectUri` and redirects to my app. This is so I can prevent 3rd party scripts from getting my authorization code. Also, if you really wanted an `implicit` flow, something like this could be useful as well. 

So while this is useful for IDPs that support multiple OAuth2 response types, this is a useful construct to have in an API more generally. I hope that adds some color.

**Comment by C45tr0** [comment]
That is awesome. I completely missed that class. Is this documented someplace? or maybe this PR should turn into adding that documentation?

**Comment by tikurahul** [comment]
Yes, this PR can perhaps turn into adding more documentation. Do you want to add a section to the `README` or create a new document which will help users navigate the API better?

**Comment by C45tr0** [comment]
I can work on that. Won't be tonight, but I should be able to do something this week.

The `README` would be easiest for me, unless you have a decent example or idea for what you would want for the separate document.

**Comment by tikurahul** [comment]
Adding a section to the `README` sounds good.

**Pull request closed without merging**
