### PR TITLE
Improve NPM experience #33

### LINKED ISSUE #33: Improve NPM experience
Hello,
There are a few things that can make NPM usage (and TypeScript experience especially) a lot better.

1. Adding a barrel. An `src/index.ts` file that `export`s all other files in that folder.
2. Adding a `main` property in `package.json` that points to the compiled result of the barrel, ex: `built/index.js`
3. Adding a `types` property in `package.json` that points to the TypeScript declaration of the barrel, ex: `built/index.d.ts`

That'll allow people to `import * as appAuth from '@openid/appauth';`, or have more specific `import`s, as they wish.

Documentation: [TypeScript Docs: Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

### P.S.

Thanks heaps for the great work on the library.

### P.P.S.

If you agree with the concept, I can also create a PR for this.

### PR DESCRIPTION
**Pull request by Meligy**
Fixes #33

### CODE REVIEW

**Comment by Meligy** [comment]
Can we please publish this if it's OK to merge?

Cheers,

**Comment by Meligy** [comment]
Good point about tests. They were added by mistake because I used a tool to generate the file.

I'll remove them and update the PR.

Regarding Node, let's include it the way it is for now. You already have good naming for them.

Ideally you'd want a neater import for these like `import * as appAuthNode from '@openid/appauth/node_support';`, but I don't know how to do this yet, and it seems not easy when you don't compile your TS files to the same folder, judging by https://github.com/Microsoft/TypeScript/issues/8305#issuecomment-343003095.

So what we have will work for now for Node.

**Comment by Meligy** [comment]
Check it now and let me know what you think. I deleted the tests references from the barrel.

**Comment by tikurahul** [comment]
Okay, this looks better. Can you also sign the CLA ?

**Comment by Meligy** [comment]
Done for both 2 CLA documents.

**Comment by Meligy** [comment]
Also received an email from Mike Leszcz saying the signature was processed.

**Pull request merged**
